[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run server:build"

[deploy]
startCommand = "npm run server:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
